---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
setwd("/Users/isabelserrano/Documents/Science/Analyses/Conplastic_Strains/files_and_analyses/change_in_mut_freq")
outdir_figures = "/Users/isabelserrano/Documents/Science/Analyses/Conplastic_Strains/files_and_analyses/change_in_mut_freq/figures"
outdir_files = "/Users/isabelserrano/Documents/Science/Analyses/Conplastic_Strains/files_and_analyses/change_in_mut_freq/files"

mut_freq_per_type_file = "files/mut_freq_per_type_wo_HFPs.txt"
mut_freq_per_type = read.table(mut_freq_per_type_file, header=TRUE, stringsAsFactors = FALSE)

comparison_studies_file = "files/comparing_mut_freq_types.txt"
comparison_studies = read.table(comparison_studies_file, header=TRUE, stringsAsFactors = FALSE)


```

This analyses was only conducted in aged mice

```{r}

sudmant_study = mut_freq_per_type %>% 
  filter(AGE_BIN == "OLD") %>%
  select(STRAIN, TISSUE, MUTATION_TYPE, FREQ) %>% 
  filter(MUTATION_TYPE == "G>A" | MUTATION_TYPE == "G>T" | MUTATION_TYPE == "T>C") %>%
  group_by(TISSUE, MUTATION_TYPE) %>% 
  summarise(AVG_MUT_FREQ_ACROSS_STRAINS = mean(FREQ)) %>% 
  rename("TYPE" = "MUTATION_TYPE", "MUT_FREQ" = "AVG_MUT_FREQ_ACROSS_STRAINS") %>%
  mutate(STUDY = "Sudmant", SPECIES = "Mouse") 
  
```

```{r}

combined_df = rbind(comparison_studies, sudmant_study)

norm_factor = combined_df %>% 
  filter(TYPE == "G>A") %>% 
  rename("NORM_FREQ_FACTOR" = "MUT_FREQ") %>%
  select(STUDY, SPECIES, TISSUE, NORM_FREQ_FACTOR)
  
summary_df = combined_df %>% 
  left_join(norm_factor, by = c("STUDY", "SPECIES", "TISSUE")) %>% 
  mutate(NORM_FREQ = MUT_FREQ/NORM_FREQ_FACTOR) %>% 
  mutate(TYPE = recode(TYPE, "G>A" = "G>A/C>T",
                       "G>T" = "G>T/C>A",
                       "T>C" = "T>C/A>G")) %>%
  mutate(LABEL = paste(STUDY, SPECIES, TISSUE, sep = "_"))

summary_df$TYPE = factor(summary_df$TYPE, level = c("G>A/C>T", "G>T/C>A", "T>C/A>G"))
summary_df$LABEL = factor(summary_df$LABEL, level = c("Sudmant_Mouse_Brain", "Makova_Mouse_Brain","Sudmant_Mouse_Liver", "Kennedy_Human_Brain", "Makova_Macaque_Liver"))

```

Plotting the frequences unnormalized 


```{r}
library(PNWColors)

bay = pnw_palette("Bay",8,type="continuous")
moth =  pnw_palette("Moth",12,type="continuous")
star = pnw_palette("Starfish", 7, type = "continuous")
refactored_spec_colors = c(star[2], bay[4], moth[6])
```

```{r}

unnorm_comp = ggplot(summary_df %>% 
                filter(LABEL %in% c("Sudmant_Mouse_Brain", "Makova_Mouse_Brain", "Kennedy_Human_Brain", "Sudmant_Mouse_Liver", "Makova_Macaque_Liver")), aes(x = TYPE, y = MUT_FREQ, fill = TYPE)) + 
  geom_bar(stat="identity", color="black", position=position_dodge()) + 
  theme_bw() + 
  facet_wrap(.~ LABEL, nrow = 1) + 
  ylab("Average \nMutation Frequency") + 
  xlab("Mutation Type") + 
  scale_fill_manual(name = "Mutation Type" , labels = c("G>A/C>T", "G>T/C>A", "T>C/A>G"), values = refactored_spec_colors) + 
  #scale_y_continuous(limits = c(0,15), breaks = c(0,1,5,10,15)) +  
  theme(strip.background=element_blank(),
        strip.text = element_blank(),
        text = element_text(family = "sans"),
        axis.text.x = element_text(angle = 45, size = 10, hjust = 1, vjust = 1), 
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        strip.text.y = element_text(size = 5),
        strip.text.x = element_text(size = 5),
        axis.text.y=element_text(size = 10),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position="none")
  
pdf(paste(outdir_figures,"/unnorm_brain_liver_mut_type_freq_comp.pdf",sep=""), width=6,height=3)
print(unnorm_comp)
dev.off() 

```

Main figure: Compares the brain for mice and humans and the liver for macaques and mice 
```{r}
library(PNWColors)

bay = pnw_palette("Bay",8,type="continuous")
moth =  pnw_palette("Moth",12,type="continuous")
star = pnw_palette("Starfish", 7, type = "continuous")
refactored_spec_colors = c(star[2], bay[4], moth[6])

comp = ggplot(summary_df %>% 
                filter(LABEL %in% c("Sudmant_Mouse_Brain", "Makova_Mouse_Brain", "Kennedy_Human_Brain", "Sudmant_Mouse_Liver", "Makova_Macaque_Liver")), aes(x = TYPE, y = NORM_FREQ, fill = TYPE)) + 
  geom_bar(stat="identity", color="black", position=position_dodge()) + 
  theme_bw() + 
  facet_wrap(.~ LABEL, nrow = 1) + 
  ylab("Normalized Average \nMutation Frequency") + 
  xlab("Mutation Type") + 
  scale_fill_manual(name = "Mutation Type" , labels = c("G>A/C>T", "G>T/C>A", "T>C/A>G"), values = refactored_spec_colors) + 
  scale_y_continuous(limits = c(0,1), breaks = c(0,0.25,0.5,0.75,1)) +  
  theme(strip.background=element_blank(),
        strip.text = element_blank(),
        text = element_text(family = "sans"),
        axis.text.x = element_text(angle = 45, size = 10, hjust = 1, vjust = 1), 
        axis.title.x = element_text(size = 11),
        axis.title.y = element_text(size = 10),
        strip.text.y = element_text(size = 5),
        strip.text.x = element_text(size = 5),
        axis.text.y=element_text(size = 10),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position="none")
  
pdf(paste(outdir_figures,"/brain_liver_mut_type_freq_comp.pdf",sep=""), width=4,height=2.5)
print(comp)
dev.off() 

```


Supp Fig: Macaque tissues 

```{r}

macaque_df = summary_df %>% 
  filter(SPECIES == "Macaque")

macaque_plot = ggplot(macaque_df, aes(x = TYPE, y = NORM_FREQ, fill = TYPE)) + 
  geom_bar(stat="identity", color="black", position=position_dodge()) + 
  theme_bw() + 
  ylab("Normalized Average \nMutation Frequency") + 
  xlab("Mutation Type") + 
  facet_wrap(.~TISSUE, nrow = 1) +
  scale_fill_manual(name = "Mutation Type" , labels = c("G>A/C>T", "G>T/C>A", "T>C/A>G"), values = refactored_spec_colors) + 
  scale_y_continuous(limits = c(0,1), breaks = c(0,0.25,0.5,0.75,1)) +  
  theme(strip.background=element_blank(),
        strip.text = element_blank(),
        text = element_text(family = "sans"),
        axis.text.x = element_text(angle = 45, size = 9, hjust = 1, vjust = 1), 
        axis.title.x = element_text(size = 11),
        axis.title.y = element_text(size = 11),
        strip.text.y = element_text(size = 12),
        strip.text.x = element_text(size = 10),
        axis.text.y=element_text(size = 9),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position="none")
  
pdf(paste(outdir_figures,"/macaque_mut_type_freq_comp.pdf",sep=""), width=3,height=2.5)
print(macaque_plot)
dev.off() 

```

Supplementary figure Makova mice 

```{r}

makova_mice_df = summary_df %>% 
  filter(SPECIES == "Mouse", STUDY == "Makova")

makova_mice_plot = ggplot(makova_mice_df, aes(x = TYPE, y = NORM_FREQ, fill = TYPE)) + 
  geom_bar(stat="identity", color="black", position=position_dodge()) + 
  theme_bw() + 
  ylab("Normalized Average \nMutation Frequency") + 
  xlab("Mutation Type") + 
  facet_wrap(.~TISSUE, nrow = 1) +
  scale_fill_manual(name = "Mutation Type" , labels = c("G>A/C>T", "G>T/C>A", "T>C/A>G"), values = refactored_spec_colors) + 
  scale_y_continuous(limits = c(0,1), breaks = c(0,0.25,0.5,0.75,1)) + 
  theme(strip.background=element_blank(),
        strip.text = element_blank(),
        text = element_text(family = "sans"),
        axis.text.x = element_text(angle = 45, size = 9, hjust = 1, vjust = 1), 
        axis.title.x = element_text(size = 11),
        axis.title.y = element_text(size = 11),
        strip.text.y = element_text(size = 12),
        strip.text.x = element_text(size = 10),
        axis.text.y=element_text(size = 9),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position="none")
  
pdf(paste(outdir_figures,"/makova_mice_mut_type_freq_comp.pdf",sep=""), width=3,height=2.5)
print(makova_mice_plot)
dev.off() 

```


Sudmant mutation frequencies for all strains and tissues 

```{r}
sudmant_all_strains_freq = mut_freq_per_type %>% 
  filter(AGE_BIN == "OLD") %>%
  select(STRAIN, TISSUE, MUTATION_TYPE, FREQ) %>% 
  filter(MUTATION_TYPE == "G>A" | MUTATION_TYPE == "G>T" | MUTATION_TYPE == "T>C") 

all_strain_norm_freq_factor = mut_freq_per_type %>%
  filter(AGE_BIN == "OLD") %>%
  filter(MUTATION_TYPE == "G>A") %>% 
  select(STRAIN, TISSUE, FREQ) %>% 
  rename("NORM_FREQ_FACTOR" = "FREQ")
  
summary_sudmant_all_strains_df = sudmant_all_strains_freq %>% 
  left_join(all_strain_norm_freq_factor, by = c("STRAIN", "TISSUE")) %>% 
  mutate(NORM_FREQ = FREQ/NORM_FREQ_FACTOR) %>%
  mutate(MUTATION_TYPE = recode(MUTATION_TYPE, "G>A" = "G>A/C>T",
                       "G>T" = "G>T/C>A",
                       "T>C" = "T>C/A>G"))

summary_sudmant_all_strains_df$STRAIN = factor(summary_sudmant_all_strains_df$STRAIN, level = c("B6", "AKR", "ALR", "FVB", "NZB"))

```


```{r}

all_strains = ggplot(summary_sudmant_all_strains_df, aes(x = MUTATION_TYPE, y = NORM_FREQ, fill = MUTATION_TYPE)) + 
  geom_bar(stat="identity", color="black", position=position_dodge()) + 
  theme_bw(base_size = 16) + 
  facet_grid(TISSUE ~ STRAIN) + 
  ylab("Normalized Average \nMutation Frequency") + 
  xlab("Mutation Type") + 
  scale_fill_manual(name = "Mutation Type",labels = c("G>A/C>T", "G>T/C>A", "T>C/A>G"), values = refactored_spec_colors) + 
  scale_y_continuous(limits = c(0,1), breaks = c(0,0.25,0.5,0.75,1)) +  
  theme(strip.background=element_blank(),
        strip.text = element_text(),
        text = element_text(family = "sans"),
        axis.text.x = element_text(angle = 45, size = 9.5, hjust = 1, vjust = 1), 
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        strip.text.y = element_text(size = 10),
        strip.text.x = element_text(size = 10),
        axis.text.y=element_text(size = 9.5),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position="none")

  
pdf(paste(outdir_figures,"/sudmant_all_strains_mut_type_freq_comp.pdf",sep=""), width=4.5,height=6)
print(all_strains)
dev.off()

```